const fs = require('fs');
const path = require('path');
const os = require('os');
const express = require('express');
const { exec } = require('child_process');

// Load env values if present
try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
} catch (err) {
  // dotenv not globally required, fallback to process.env
}

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Path to telemetry JSON file generated by python telemetry collector
const TELEMETRY_PATH = path.join(__dirname, '..', 'telemetry_node.json');
const CONFIG_PATH = path.join(__dirname, '..', 'config', 'config.json');

/**
 * Helper to load config file safely
 */
function loadConfig() {
  if (fs.existsSync(CONFIG_PATH)) {
    try {
      return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    } catch (err) {
      // JSON syntax error
    }
  }
  return {};
}

/**
 * Helper to run shell commands safely
 */
function runCommand(command) {
  return new Promise((resolve) => {
    exec(command, (error, stdout, stderr) => {
      if (error) {
        resolve({ success: false, error: error.message, stderr });
      } else {
        resolve({ success: true, stdout, stderr });
      }
    });
  });
}

/**
 * GET /api/layout
 * Serves dynamic layout configurations (theme details and polling loops).
 */
app.get('/api/layout', (req, res) => {
  const layoutPath = path.join(__dirname, 'dashboard_layout.json');
  if (fs.existsSync(layoutPath)) {
    try {
      const layout = JSON.parse(fs.readFileSync(layoutPath, 'utf8'));
      return res.json(layout);
    } catch (err) {
      // Fall through on JSON syntax errors
    }
  }
  res.json({});
});

/**
 * GET /api/metrics
 * Pulls telemetry metrics. Falls back to Node OS stats if telemetry collector is not running.
 */
app.get('/api/metrics', (req, res) => {
  if (fs.existsSync(TELEMETRY_PATH)) {
    try {
      const raw = fs.readFileSync(TELEMETRY_PATH, 'utf8');
      const metrics = JSON.parse(raw);
      metrics.collector_active = true;
      return res.json(metrics);
    } catch (err) {
      // JSON parse error, fall through to OS fallback
    }
  }

  // Fallback system metrics if daemon is not running
  const totalMem = os.totalmem();
  const freeMem = os.freemem();
  const usedMem = totalMem - freeMem;
  const memPercent = Math.round((usedMem / totalMem) * 100);
  const cpus = os.cpus();
  const cores = cpus.length;
  
  res.json({
    timestamp: new Date().toISOString(),
    collector_active: false,
    system_grade: "B",
    average_load_percent: 25.0,
    os_platform: process.platform,
    uptime: Math.round(os.uptime()),
    cpu: {
      percent: 20.0,
      cores: cores,
      threads: cores
    },
    memory: {
      total_bytes: totalMem,
      available_bytes: freeMem,
      used_bytes: usedMem,
      percent: memPercent
    },
    disk: {
      total_bytes: 500 * 1024 * 1024 * 1024,
      free_bytes: 250 * 1024 * 1024 * 1024,
      used_bytes: 250 * 1024 * 1024 * 1024,
      percent: 50
    },
    gpu: {
      available: false,
      note: "Telemetry collector daemon is inactive. Launch python telemetry.py to check GPU acceleration."
    }
  });
});

/**
 * GET /api/pm2
 * Resolves list of running processes in PM2 via 'pm2 jlist'
 */
app.get('/api/pm2', async (req, res) => {
  const result = await runCommand('pm2 jlist');
  if (!result.success) {
    return res.json({
      pm2_active: false,
      processes: [],
      error: "PM2 not running or not found in PATH."
    });
  }

  try {
    const list = JSON.parse(result.stdout);
    const processes = list.map(p => ({
      pid: p.pid,
      id: p.pm_id,
      name: p.name,
      status: p.pm2_env.status,
      uptime: Math.round((Date.now() - p.pm2_env.pm_uptime) / 1000),
      restarts: p.pm2_env.restart_time,
      cpu: p.monit ? p.monit.cpu : 0,
      memory: p.monit ? p.monit.memory : 0
    }));
    res.json({
      pm2_active: true,
      processes
    });
  } catch (err) {
    res.json({
      pm2_active: true,
      processes: [],
      error: "Failed to parse PM2 output."
    });
  }
});

/**
 * POST /api/pm2/control
 * Send controls to PM2 processes (start, stop, restart)
 */
app.post('/api/pm2/control', async (req, res) => {
  const { action, id } = req.body;
  if (!action || id === undefined) {
    return res.status(400).json({ error: "Missing action or process id." });
  }

  const allowedActions = ['start', 'stop', 'restart'];
  if (!allowedActions.includes(action)) {
    return res.status(400).json({ error: "Invalid action type." });
  }

  const idStr = String(id).trim();
  if (!/^[a-zA-Z0-9_\-]+$/.test(idStr)) {
     return res.status(400).json({ error: "Invalid process identifier pattern." });
  }

  console.log(`[PM2 Control] Executing 'pm2 ${action} ${idStr}'`);
  const result = await runCommand(`pm2 ${action} ${idStr}`);
  
  if (result.success) {
    res.json({ success: true, message: `Successfully executed '${action}' on process '${idStr}'` });
  } else {
    res.status(500).json({ error: `Command failed: ${result.error}`, details: result.stderr });
  }
});

/**
 * GET /api/ollama
 * Interfaces with the local Ollama API to verify status and retrieve downloaded models
 */
app.get('/api/ollama', async (req, res) => {
  const config = loadConfig();
  
  const defaultHost = config.ollama ? config.ollama.default_host : 'http://127.0.0.1:11434';
  const host = process.env.OLLAMA_HOST || defaultHost;
  const cleanHost = host.startsWith('http') ? host : `http://${host}`;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2000);

    const response = await fetch(`${cleanHost}/api/tags`, { signal: controller.signal });
    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error(`Ollama API responded with status ${response.status}`);
    }

    const data = await response.json();
    res.json({
      ollama_active: true,
      endpoint: cleanHost,
      models: data.models || []
    });
  } catch (err) {
    res.json({
      ollama_active: false,
      endpoint: cleanHost,
      models: [],
      error: `Could not reach Ollama engine: ${err.message}`
    });
  }
});

/**
 * POST /api/ollama/pull
 * Trigger download of an Ollama model asynchronously
 */
app.post('/api/ollama/pull', async (req, res) => {
  const { name } = req.body;
  if (!name) {
    return res.status(400).json({ error: "Model name is required." });
  }

  const config = loadConfig();
  const defaultHost = config.ollama ? config.ollama.default_host : 'http://127.0.0.1:11434';
  const host = process.env.OLLAMA_HOST || defaultHost;
  const cleanHost = host.startsWith('http') ? host : `http://${host}`;

  console.log(`[Ollama Pull] Requesting pull for model: ${name}`);
  
  try {
    const response = await fetch(`${cleanHost}/api/pull`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, stream: false })
    });

    if (!response.ok) {
      throw new Error(`Ollama pull command failed with code ${response.status}`);
    }

    const result = await response.json();
    res.json({ success: true, result });
  } catch (err) {
    res.status(500).json({ error: `Pull failed: ${err.message}` });
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`==================================================`);
  console.log(`  🛸 Kinetix IDE Console Server running!`);
  console.log(`  Local Endpoint: http://localhost:${PORT}`);
  console.log(`  Tailscale Endpoint: http://${os.hostname()}:${PORT}`);
  console.log(`==================================================`);
});
